directory: ~/Music/Reverb
library: ~/Music/Reverb/beet.db

plugins:
  - musicbrainz
  # - spotify
  - filetote
  - fetchart
  - embedart
  - playlist
  - importfeeds

paths:
  default: $albumartist/$album/$track $title
  singleton: $albumartist/Non-Album/$title

spotify:
  data_source_mismatch_penalty: 0.8

filetote:
  patterns:
    artworkdir:
      - '[sS]cans?/'
      - '[aA]rtworks?/'
      - '[cC]overs?/'
      - '[bB]ooklet/'

    # match loose image files at album root
    artworkfiles:
      - 'cover.*'
      - 'folder.*'
      - '*.jpg'
      - '*.JPG'
      - '*.jpeg'
      - '*.png'
      - '*.tif'
      - '*.tiff'
      - '*.gif'
      - '*.pdf'

  # where to put them in your library
  paths:
    default: $albumartist/$album/$track $title
    artworkdir:  $albumpath/artworks/$old_filename
    artworkfiles: $albumpath/artworks/$old_filename

embedart:
  compare_threshold: 10

playlist:
  auto: yes
  relative_to: ~/Music/Playlists
  playlist_dir: ~/Music/Playlists

importfeeds:
  formats: m3u_session
  dir: ~/Music/Playlists
  relative_to: ~/Music/Playlists
  m3u_name: imported
